apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      volumes:
        - name: data-volume
          emptyDir: {}
      initContainers:
        - name: data-init
          image: ilyesnajjari/data-image:v1
          command: ["sh", "-c", "cp -r /data/* /data-dest/"]
          volumeMounts:
            - name: data-volume
              mountPath: /data-dest
      containers:
        - name: ingestion
          image: ilyesnajjari/ingestion-service:latest