name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies for all services
      run: |
        python -m pip install --upgrade pip
        # Installer les requirements globaux si existants
        pip install -r requirements.txt || true

        # Installer les requirements de chaque service sauf train-service
        for req in services/*/requirements.txt; do
          if [[ "$req" != "services/train-service/requirements.txt" ]]; then
            pip install -r "$req"
          fi
        done

        # Installer les requirements spécifiques à train-service
        if [ -f services/train-service/requirements-base.txt ]; then
          pip install -r services/train-service/requirements-base.txt
        fi

        # Installer les dépendances du frontend
        if [ -f frontend/requirements.txt ]; then
          pip install -r frontend/requirements.txt
        fi

    - name: Run tests per service
      run: |
        set -e  # Arrête le script en cas d'erreur

        for service in frontend services/*; do
          if [ -d "$service" ]; then
            echo "🚀 Running tests in $service..."
            pytest "$service"
          fi
        done
